[package]
name = "irc"
version = "0.1.0"
authors = ["Calum Leslie <calumleslie@gmail.com>"]

[dependencies]
nom = "1.2.4"
log = "0.3.6"
openssl = "0.9.1"
clippy = {version = "*", optional = true}

[features]
default = []
